org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1
loom_version=1.17.17
jei_version=19.43.0.393
emi_version=1.1.24+1.21.1+fabric
emi_modrinth_project_id=fRiHVvU7
emi_modrinth_version_id=on5GT1qh

mod_id=jei_biome
mod_name=JEI Biome
mod_license=All Rights Reserved
mod_version=1.5fix
mod_group_id=com
mod_authors=hp
mod_description=View biome mob spawns, ore distribution, and related biome block information directly in JEI.
